### ISSUE TITLE
Getting an issue in an established game

### ISSUE THREAD

**Issue by A7207** [vtt-lair/player-pronouns#8]
Hello there! I absolutely love this module and have been using it in all of my games.

I do, however, have an issue in a current game where I do not have the option of selecting pronouns in the player configuration menu, nor does anything show up.

I have been getting the following error:

VM12643:8
Error: This is not a registered game setting
    at ClientSettings.get (foundry.js:1146)
    at Object.grabSavedSettings (player-pronouns.js:260)
    at playerPronounsReady (player-pronouns.js:297)
    at Function._call (eval at <anonymous> (libWrapper-consts.js:8), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at Game.setupGame (foundry.js:4307)
    at async Game._initializeGameView (foundry.js:5117)
    at async Game.initialize (foundry.js:4202)

**Comment by vtt-lair** [comment]
@A7207 can you please supply of screenshot of your settings while I investigate this?

**Comment by vtt-lair** [comment]
Ahhh, I think I know what the issue is. What game system is this in?

**Comment by vtt-lair** [comment]
@A7207 I have fixed it and it should now work for you. This issue was that there is a setting to save the selected pronouns to the actor's gender field... however I only show said setting for supported game systems (currently 5e (DnD5e, DNDJP5e & sw5e) and PF2e). Unfortunately, when trying to grab the setting when getting the saved settings values, I was still checking for that gender setting even though it wasn't available.

I've fixed that. If that is functionality you would also like access too, let me know what game systems you use and I'll see if I can figure out what the gender variable is called for the actors in those systems.

**Comment by A7207** [comment]
@vtt-lair I would love to have access for that in PF1e, and thank you so much for taking a look at it. I really appreciate this module, as do my players.

**Comment by vtt-lair** [comment]
@A7207 I'm planning on changing the way I've implemented that setting to always be available and default to a specific variable name in the hope that the majority of game systems uses the same variable name. I'll test it on PF1 and just add it as one of the confirmed systems once that is done. Expect the update round about the weekend or start of next week.
